ALTER TABLE files
ADD "group" VARCHAR,
ADD user_readable BOOLEAN NOT NULL DEFAULT TRUE,
ADD user_writable BOOLEAN NOT NULL DEFAULT TRUE,
ADD user_executable BOOLEAN NOT NULL DEFAULT FALSE,
ADD group_readable BOOLEAN NOT NULL DEFAULT TRUE,
ADD group_writable BOOLEAN NOT NULL DEFAULT FALSE,
ADD group_executable BOOLEAN NOT NULL DEFAULT FALSE,
ADD other_readable BOOLEAN NOT NULL DEFAULT FALSE,
ADD other_writable BOOLEAN NOT NULL DEFAULT FALSE,
ADD other_executable BOOLEAN NOT NULL DEFAULT FALSE,
ADD platform_creation VARCHAR
